[package]
name = "turso_dotnet"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
async-io = "2.4.0"
async-task = "4.7.1"
interoptopus = "0.15.0-alpha.6"
libsql = "0.6.0"
tokio = "1.45.1"