[package]
name = "turso_dotnet"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
async-io = "2.4.0"
async-task = "4.7.1"
interoptopus = { path = "../../dependency/interoptopus/crates/core" }
libsql = "0.6.0"
tokio = "1.45.1"