[package]
name = "turso_dotnet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-io = "2.4.0"
async-task = "4.7.1"
libsql = "0.6.0"
[build-dependencies]
csbindgen = "1.9.3"